food/urls.py
from django.conf.urls import url
from . import views

app_name="food"

urlpatterns = [
    #/food/ homepage with no extra information
    url(r'^$', views.sfood,name="sfood"),


    url(r'^about_us$', views.about_us,name="about_us"),

    url(r'^contact_us$', views.contact_us,name="contact_us"),

    #url(r'^test$', views.test,name="test"),
    

    # /food/ homepage with no extra information
    url(r'^vegetable$', views.Vindex, name="vegetables"),

    url(r'^fruit$', views.Findex, name="fruits"),

    # /food/71(id)/ ^ represent the begning and $ ssign represent the end both at the same time
    url(r'^detail/(?P<album_id>[0-9]+)/$', views.detail, name="detail"),


    # /food/album/delete/
    #url(r'^album/(?P<pk>[0-9]+)/buy/$', views.Vindex, name='album-buy'),

    # /food/71(id)/ ^ represent the begning and $ ssign represent the end both at the same time

    # for registration


   # url(r'^carts/$', views.cart_home, name="cart"),
   # url(r'^carts/cart_update/$', views.cart_update, name="update"),

    url(r'^cart/$', views.cart_detail, name='cart_detail'),
    url(r'^cart/add/(?P<product_id>[0-9]+)/$', views.cart_add, name='cart_add'),
    url(r'^cart/remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

foodie/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from . import views




urlpatterns = [
    #path('admin/', admin.site.urls),
    url('^admin/', admin.site.urls),
    url(r"^food/", include('food.urls',namespace='food')),

    url(r"^orders/", include('orders.urls',namespace='orders')),
    url(r'^$', views.main, name='main'),

    # for registration
    url(r'^register$', views.UserFormView.as_view(), name="register"),
    url(r'^logout_user/$', views.logout_user, name="logout_user"),

    url(r'^login_user/$', views.login_user, name="login_user"),


]
if settings.DEBUG:
   urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^order_created/$', views.order_created, name='order_created'),

    url(r'^your_order/$', views.your_order, name='your_order'),
]

food/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import Permission, User
from django.conf import settings
from django.db.models.signals import pre_save
from .utils import unique_slug_generator

User=settings.AUTH_USER_MODEL



class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    nick_names = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=150,blank=True, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

   # class Meta:
   #     ordering = ('name', )
    #    verbose_name = 'category'
   #     verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

  #  def get_absolute_url(self):
  #      return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category  , on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    nick_names = models.CharField(max_length=400, db_index=True)
    slug = models.SlugField(max_length=150,blank=True, unique=True ,db_index=True)
    description = models.TextField(blank=True)
    b_price = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    weight = models.CharField(max_length=15, db_index=True)

    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    logo=models.FileField()

    #class Meta:
      #  ordering = ('name', )
     #   index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

#    def get_absolute_url(self):
    #    return reverse('shop:product_detail', args=[self.id, self.slug])



def category_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug= unique_slug_generator(instance)

pre_save.connect(category_pre_save_receiver,sender=Category)

def product_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug= unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver,sender=Product)

food/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)#to take passwords
    cpassword=forms.CharField(widget=forms.PasswordInput,label="confirm_password")#to take passwords
    phone_no=forms.CharField(widget=forms.TextInput,label="enter_phone_number :")

#attrs={'class':'form-control form-control-sm','placeholder':'+91 1234567890'},

    class Meta:
        model=User
        fields=['username','email','password','cpassword','phone_no']




PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 50)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

food/views.py
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render,redirect,get_object_or_404
from django.views import generic
from django.views.generic import View
from .models import Category,Product
from .cart import Cart
from django.template import loader
from django.db.models import Q
from django.views.decorators.http import require_POST

from food.forms import CartAddProductForm




def Vindex(request):
    album = get_object_or_404(Category, pk=2)
    cart_product_form = CartAddProductForm()
    # template = loader.get_template('music/index.html')#we do not wrtei template becuse by defulat django is set up to see in templates folder so take care
    return render(request, 'food/index.html', {'album': album, 'type':"vegetables", 'cart_product_form':cart_product_form})



def Findex(request):
    album = get_object_or_404(Category, pk=1)
    cart_product_form = CartAddProductForm()
    # template = loader.get_template('music/index.html')#we do not wrtei template becuse by defulat django is set up to see in templates folder so take care
    return render(request, 'food/index.html', {'album': album, 'type':"vegetables", 'cart_product_form':cart_product_form})



def detail(request, album_id):
    album = get_object_or_404(Product,pk=album_id)
    cart_product_form = CartAddProductForm()

    return render(request, 'food/detail.html', {'album': album ,'cart_product_form': cart_product_form})
    #in this we will get albumname_albumartist as becouse we done in models to give only title f album then doalbum.album_title




def sfood(request):
    category = Category.objects.all()
    product = Product.objects.all()
    template = loader.get_template('food/sfood.html')#we do not wrtei template becuse by defulat django is set up to see in templates folder so take care
    cart_product_form = CartAddProductForm()

    query = request.GET.get("q")
    if query:
        category = category.filter(
            Q(name__icontains=query) |
            Q(nick_names__icontains=query)
        ).distinct()

        product = product.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query) |
            Q(nick_names__icontains=query) |
            Q(price__icontains=query)
        ).distinct()

        return render(request, 'food/sfood.html', {
            'category': category,
            'product': product,
            'cart_product_form': cart_product_form,
        })

    else:
        return render(request, 'food/sfood.html', {
            'category': category,
            'product': product,
            'cart_product_form': cart_product_form,
        })


def about_us(request):
    return render(request,'food/about.html',{'food':"ayush",})

def contact_us(request):
    return render(request,'food/about.html',{'food':"contact",})


'''
def cart_create(user=None):
    cart_obj=Cart.objects.create(user=None)
    print('new cart creted')
    return cart_obj

def cart_home(request):
    #del request.session['cart_id']
    request.session['cart_id']=int("12")#we set y default that d is thre whether it belongs to ue or not
    cart_id=request.session.get("cart_id",None)
#we are creatin
    # g nione user because to stor data of outsiders withoue loginuserrs

    if cart_id is None:# and isinstance(cart_id,int):
        cart_obj=cart_create()
        request.session['cart_id']=cart_obj.id
    else:
        qs=Cart.objects.filter(id=cart_id)#this means catr exist adn wherther t has data or nt it checks

        if qs.count()==1:#check thrt therr i s any cart daa or nto or its object
            print('cart id exist')
            cart_obj=qs.first()
        else:
            cart_obj=cart_create()#if threr is no data then create
            request.session['cart_id']=cart_obj.id#this taes the above id only


    return render(request,"food/carts.html",{})



'''


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('food:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('food:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    a=0
    message=''
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        a+=1
    if a==0:
        message='Please Add item to the cart before shopping'
    return render(request, 'food/cart_detail.html', {'cart': cart,'message':message})

food/templates/food/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Vegetables {% endblock %}</title>

    <!--loads   the  to your static file-->
{% load staticfiles %}


  {% block basel %}

{% endblock %}


     <link rel="shortcut icon" type="image/png" href="{%  static 'food/images/icons/title.png' %}" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'food/Footer-with-map.css' %}">



</head>
<body>
<nav class="nav navbar-inverse fixed1">

    <div class="container-fluid  ">

        <!--logo -->

       <div class="navbar-header ">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar1 ">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
           <button type="button" class="navbar-toggle btn-info" data-toggle="collapse" data-target="#topNavBar ">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
           </button>

            <a class="navbar-brand" href="{% url 'main' %}">Sniccy  &nbsp <small><small>Fresh, Low price,FastDelivery,....</small></small>{% comment %}<img src="{% static 'food/images/icons/wname3.png' %}" style="margin-top:0px; height:60px; width:150px;">{% endcomment %}</a>
        </div>



        <!-- Items inside navbar -->
    <div class="collapse navbar-collapse" id="topNavBar">

        <div class="col-lg- navbar-right ">
             <ul class="nav navbar-nav">



             <li class="dropdown bg-dark">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About Us <span class="caret"></span></a>

             <ul class="dropdown-menu bg-dark">


                 <li class="">
                <a href="{% url 'food:about_us' %}">
                    <span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>&nbsp;About
                </a>
            </li>
                          <li role="separator" class="divider"></li>




            <li class="">

 <a href="{% url 'food:contact_us' %}">
                    <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>&nbsp; Contact Us
                </a>
            </li>

          </ul>
        </li>




    {% if user.is_authenticated %}
            <li class="">

 <a href="{% url 'logout_user' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; LogOut
                </a>
            </li>

                {% else %}


             <li class="dropdown bg-dark">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Log In<span class="caret"></span></a>

             <ul class="dropdown-menu bg-dark" style="border-radius:20px;">

            <li class="">

 <a href="{% url 'login_user' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; LogIn
                </a>
            </li>

                                           <li role="separator" class="divider"></li>


            <li class="">

 <a href="{% url 'register' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Sign Up
                </a>
            </li>

             </ul>
             </li>


            {% endif %}



             </ul>
        </div>
    </div>
    </div>
    </nav>

<nav class="nav navbar-inverse sticky1 fixed1">


    <div class="collapse navbar-collapse" id="topNavBar1">
<div class="col-12 sticky1 ">
        <ul class="nav navbar-nav">
            <li class="">
                <a href="{% url 'food:vegetables' %}">
                    <span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>&nbsp;Vegetables
                </a>
            </li>

            <li class="">
                <a href="{% url 'food:fruits' %}">
                    <span class="glyphicon glyphicon-apple" aria-hidden="true"></span>&nbsp;Fruit
                </a>
            </li>


        </ul>
<div class="">
        <form class="navbar-form navbar-left sbtnf"  role="search" method="get" action="{% url 'food:sfood' %}">

            <div class="form-group ">
            <input type="text" class="form-control" id="sbtni" name="q" value="{{ request.GET.q }}" placeholder="Search...">
            </div>

            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;</button>
        </form>

</div>


        <ul class="nav navbar-nav navbar-right">


                                <li class="bg-dark">
                <a href="{% url 'food:cart_detail' %}">
                    <span class="glyphicon glyphicon-shopping-cart"  aria-hidden="true"></span>&nbsp;My Cart
                </a>
            </li>



                     <li >
                <a href="{% url 'orders:your_order' %}">
                    <span class="glyphicon glyphicon-shopping-cart"  aria-hidden="true"></span>&nbsp;My Orders
                </a>
            </li>




            <li class="">

            </li>
        </ul>
</div>
    </div>

</nav>





{% block body %}
{% endblock %}




    <footer id="myFooter">
        <div class="container">
            <div class="row">

<div style="text-align:center; padding-right:2%; padding-left:auto;">
                <div class="col-sm-4 col-lg-4">

           <button type="button" class="navbar-toggle btn-info f-col" data-toggle="collapse" data-target="#topNavBar4">
 <h5>About us</h5>
           </button>

            <!-- Items inside navbar -->
    <div class="collapse navbar-collapse" id="topNavBar4">

             About us

              <ul class="nav navbar-na">
                        <li><a href="{% url 'food:about_us' %}">Company Information</a></li>
                        <li><a href="{% url 'food:contact_us' %}">Contact us</a></li>
                    </ul>
				</div>
				</div>





                <div class="col-sm-4 col-lg-4">
                    <button type="button" class="navbar-toggle btn-info f-col" data-toggle="collapse" data-target="#topNavBar2">
 <h5>Legal</h5>
           </button>

            <!-- Items inside navbar -->
    <div class="collapse navbar-collapse" id="topNavBar2">
         Legal
            <ul class="nav navbar-na">
                        <li><a href="{% url 'food:fruits' %}">Terms of Service</a></li>
                        <li><a href="{% url 'food:fruits' %}">Terms of Use</a></li>
                        <li><a href="{% url 'food:fruits' %}">Privacy Policy</a></li>
                    </ul>
				</div>




            </div>

                        <div class="col-sm-4 col-lg-4">


           <button type="button" class="navbar-toggle btn-info f-col" data-toggle="collapse" data-target="#topNavBar3">
 <h5>Home</h5>
           </button>

            <!-- Items inside navbar -->
    <div class="collapse navbar-collapse" id="topNavBar3">

            Home
              <ul class="nav navbar-na">
                        <li><a href="{% url 'main' %}">Home</a></li>
                        <li><a href="{% url 'register' %}">Sign up</a></li>
                    </ul>
				</div>
    </div>
            </div>
				</div>



            </div>

            <!-- Here we use the Google Embed API to show Google Maps. -->
            <!-- In order for this to work in your project you will need to generate a unique API key.  -->
<div style="width: 100%"><iframe width="100%" height="200" src="https://maps.google.com/maps?width=100%&amp;height=200&amp;hl=en&amp;q=holychild%20school%20sonipat%20sectr%201a+(vegiefy)&amp;ie=UTF8&amp;t=&amp;z=16&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"><a href="https://www.maps.ie/map-my-route/">Create route map</a></iframe></div><br>

        <!--<div class="social-networks">
            <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
            <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
        </div>
		-->
        <div class="footer-copyright">
            <p>© 2016 Copyright Text </p>
        </div>
    </footer>



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{% block bases %}

{% endblock %}

</body>
</html>

food/templates/food/cart_detail.html
{% extends 'food/base.html' %}
{% load staticfiles %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block body %}
<div class="container" style="min-height:500px;">
<div class="row" style="margin-top: 6%">
    {% if message %}
    <h3>{{ message }}</h3>
    {% endif %}
        <h2>Your Shopping Cart
<br>
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, . {{ cart.get_total_price }}Rs
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
<br>
        </h2>
            <table class="table table-striped table-hover container">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Rem..</th>
                        <th>Unit Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{% url 'food:detail' product.id %}">
                                    <img src=" {{ product.logo.url }}" class="t-img" alt="..." style="max-height:60px; max-width:40px;">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url 'food:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}{{ product.weight }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url 'food:cart_remove' product.id %}"> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                            </td>
                            <td>{{ item.price }} rs/{{ product.weight }}</td>

                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="3"></td>
                    <td colspan="num"><b>{{ cart.get_total_price }} Rs</b></td>
                </tr>
                </tbody>
            </table>
    {% widthratio item.price 1 5 %}
        <p class="text-right">
            <a href="{% url 'food:vegetables' %}" class="btn btn-default">Continue Shopping</a>
                        <a href="{% url 'orders:order_create'    %}" class="btn btn-primary">Checkout</a>

        </p>
        </div>
    </div>
{% endblock %}

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block title %}{{ album }}{% endblock %}


{% block body %}


<div class="container-fluid albums-container" style="margin-top:30px;">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                                       <a href="{% url 'food:detail' album.id %}">
                    <div style="overflow:hidden; " class="i-area">
                            <img src="{{ album.logo.url }}" class="img-responsive" style="height:200px; width:100%;">
                    </div>
                        </a>


                    <h1>{{ album.name }} <small>{{ album.amount }}</small></h1>
                    <h2>{{ album.description }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
  <form action="{% url 'food:cart_add' album.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_product_form }}
                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>


              </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h2>{{album.name}} ({{ album.nick_names  }})</h2>
                    <hr style="height:4px;">

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <h2>{{ album.description }}
                   <br><br><s>before Price: {{ album.b_price }} </s>
                        <br></br>Now={{ album.price }}</h2>

                </div>
            </div>
               <ul class="nav nav-pills" style="margin-bottom: 10px;">


                <li role="presentation" class="active"><a href="{% url 'food:sfood'  %}">View All Fruits & vegetables</a></li>



              </ul>

        </div>

    </div>

</div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}



{% block albums_active %}active{% endblock %}

{% block body %}

{% if vtype %}
<h2>my name is veg</h2>
{{ type }}
    {% else %}
<h2>my name is fruit</h2>
{% endif %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12" >
            <h3>{{ user.username }}'s Albums </h3>
        </div>


        {% if album %}

        {% for food in album.product_set.all %}

        {% if food.available == True %}
                   <div class="col-sm-4 col-lg-3">
                    <div class="thumbnail">
                        <!--here i ahe used if statenetn becouse in index view we have to display particular category of fruit or vegtables if vtype means the requet is from veg olumn and fyype means requst from fruit table -->
                            <a href="{% url 'food:detail' food.id %}">
                    <div style="overflow:hidden; " class="i-area">
                            <img src="{{ food.logo.url }}" class="img-responsive" style="height:200px; width:100%;">
                    </div>
                        </a>

                        <div class="caption">
                            <h2>{{ food.name }}<small> ({{ food.nick_names }})</small></h2><small class="pull-right lead"><s>Rs: {{ food.b_price }}</s><br>  Rs: {{ food.price }}/{{ food.weight}} </small>
                            <h4>{{ album.descriptio }}  </h4>

                            <!-- View Details --
>

                           <a href="{% url 'food:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>!>-->
<br>

                                      <form action="{% url 'food:cart_add' food.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_product_form }}<br>
                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>


                            <!-- Delete Album -->


                        </div>
                    </div>
                </div>
        {% endif %}
{% endfor %}

                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        {% else %}
            <div class="col-sm-12">
                <br>
                not any album
            </div>
        {% endif %}
    </div>
</div>

    {% endblock %}

food/templates/food/sfood.html
{% extends 'food/base.html' %}



{% block albums_active %}active{% endblock %}

{% block body %}


<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12" >
            <h3>{{ user.username }}'s Albums {{ user.first_name }}</h3>
        </div>

{% if product %}
            {% for album in product %}
                    <div class="col-sm-4 col-lg-3">
                    <div class="thumbnail">
                        <!--here i ahe used if statenetn becouse in index view we have to display particular category of fruit or vegtables if vtype means the requet is from veg olumn and fyype means requst from fruit table -->
                        <a href="{% url 'food:detail' album.id %}">
                    <div style="overflow:hidden; " class="i-area">
                            <img src="{{ album.logo.url }}" class="img-responsive" style="height:200px; width:100%;">
                    </div>
                        </a>

                        <div class="caption">
                            <h2>{{ album.name }}<small> ({{ album.nick_names }})</small></h2><small class="pull-right lead"><s>Rs: {{ album.b_price }}</s><br>  Rs: {{ album.price }}/{{ album.weight}} </small>
                            <h4>{{ album.descriptio }}  </h4>

                            <!-- View Details --
>

                           <a href="{% url 'food:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>!>-->
<br>

                                      <form action="{% url 'food:cart_add' album.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_product_form }}<br>
                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>


                            <!-- Delete Album -->


                        </div>
                    </div>
                </div>
                    {% endfor %}

                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        {% else %}
            <div class="col-sm-12">
                <br>
                not any album
            </div>
        {% endif %}







    </div>
</div>
    {% endblock %}