food/urls.py
from django.conf.urls import url
from . import views

app_name="food"

urlpatterns = [
    #/food/ homepage with no extra information
    url(r'^$', views.sfood,name="sfood"),


    url(r'^about_us$', views.about_us,name="about_us"),

    url(r'^contact_us$', views.contact_us,name="contact_us"),

    #url(r'^test$', views.test,name="test"),
    

    # /food/ homepage with no extra information
    url(r'^vegetable$', views.Vindex, name="vegetables"),

    url(r'^fruit$', views.Findex, name="fruits"),

    # /food/71(id)/ ^ represent the begning and $ ssign represent the end both at the same time
    url(r'^detail/(?P<album_id>[0-9]+)/$', views.detail, name="detail"),


    # /food/album/delete/
    #url(r'^album/(?P<pk>[0-9]+)/buy/$', views.Vindex, name='album-buy'),

    # /food/71(id)/ ^ represent the begning and $ ssign represent the end both at the same time

    # for registration


   # url(r'^carts/$', views.cart_home, name="cart"),
   # url(r'^carts/cart_update/$', views.cart_update, name="update"),

    url(r'^cart/$', views.cart_detail, name='cart_detail'),
    url(r'^cart/add/(?P<product_id>[0-9]+)/$', views.cart_add, name='cart_add'),
    url(r'^cart/remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

foodie/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from . import views




urlpatterns = [
    #path('admin/', admin.site.urls),
    url('^admin/', admin.site.urls),
    url(r"^food/", include('food.urls',namespace='food')),

    url(r"^orders/", include('orders.urls',namespace='orders')),
    url(r'^$', views.main, name='main'),

    # for registration
    url(r'^register$', views.UserFormView.as_view(), name="register"),
    url(r'^logout_user/$', views.logout_user, name="logout_user"),

    url(r'^login_user/$', views.login_user, name="login_user"),


]
if settings.DEBUG:
   urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^order_created/$', views.order_created, name='order_created'),

    url(r'^your_order/$', views.your_order, name='your_order'),
]

orders/models.py
from django.db import models
from food.models import Product
from django.contrib.auth.models import Permission, User


class Order(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    phone_no = models.IntegerField()
    address = models.CharField(max_length=150)
    postal_code = models.CharField(max_length=30)
    city = models.CharField(max_length=100)
    total_cost=models.DecimalField(max_digits=15, default=22,decimal_places=2)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    total_i_price=models.DecimalField(max_digits=15, decimal_places=2)


    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order

        fields = ['first_name', 'last_name','phone_no', 'email', 'address', 'postal_code', 'city' ]

orders/views.py
from django.shortcuts import render,redirect
from .models import OrderItem,Order
from .forms import OrderCreateForm
from food.cart import Cart
from django.contrib.auth.decorators import login_required
from orders.models import Order
from decimal import Decimal
from django.shortcuts import get_object_or_404



@login_required(login_url='/login_user')
def order_create(request):
        cart = Cart(request)
        a=0
        for item in cart:
            a=a+1

        if  a != 0 :
            if request.method == 'POST':
                form = OrderCreateForm(request.POST)
                if form.is_valid():
                    order = form.save()
                    order.user=request.user
                    order.total_cost=sum(Decimal(item['price']) * item['quantity'] for item in cart)

                    for item in cart:
                        OrderItem.objects.create(
                            order=order,
                            product=item['product'],
                            price=item['price'],
                            quantity=item['quantity'],
                            total_i_price=item['price']*item['quantity']
                        )
                    cart.clear()
                order.save()
                return render(request, 'orders/order/created.html', {'order': order})


            else:
                form = OrderCreateForm()
            return render(request, 'orders/order/create.html', {'form': form})
        else:
            return redirect('food:cart_detail')


@login_required(login_url='/login_user')
def your_order(request):
    orders = Order.objects.filter(user=request.user)
    ialbum = get_object_or_404(Order, pk=2)

    order_items=OrderItem.objects.all()
    return render(request,'orders/order/your_order.html', {'orders':orders,'ialbum':ialbum ,'order_items':order_items})

@login_required(login_url='/login_user')
def order_created(request):
    return render(request, 'orders/order/created.html')

orders/templates/orders/order/create.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8">
                <h4 class="page-header">Checkout</h4>
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}<br>

                    <input type="submit" class="btn btn-primary" value="Submit order">
                </form>
            </div>
            <div class="col-md-4">
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }}x {{ item.product.name }}
                        <span>Kshs. {{ item.total_price }}</span>
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: kshs. {{ cart.get_total_price }}</li>
                </ul>

            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block body %}
    <div class="container" style="min-height:400px;">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8 col-md-offset-2" style="min-height:350px;">
                <h3 class="page-header ">Thank You For Shopping With Us
                </h3>
                <p class="lead">Your order has been successfully completed. Your order ID is <strong>{{ order.id }}</strong>.<br> Ordered will be delivered within  1 to 2 Hour .So we will contact u Soon,,</p>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order/your_order.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block body %}

        {% if orders %}



<div class="container" style="min-height:500px;">
<div class="row" style="margin-top: 4%">
        <h2>Your Shopping orders

        </h2><hr>






    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
<h2>YOur  recent orders</h2>


{% for album in orders %}
             {% if not album.paid %}

  <div class="panel panel-default" style="border-radius:40px;">
    <div class="panel-heading" role="tab" id="a{{ album.id }}" style="padding:15px; border-radius:15px 15px 5px 5px;">
         <a role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ album.id }}" aria-expanded="false" aria-controls="{{ album.id }}" >
      <h4 class="panel-title" style="color:black;">
          Id={{ album.id }} <span class="pull-right ">{{ album.created }}</span>
      </h4>
         </a>

    </div>
    <div id="{{ album.id }}" class="panel-collapse collapse " role="tabpanel" aria-labelledby="a{{ album.id }}">
      <div class="panel-body">

     <strong>     Name={{ album.first_name }} &nbsp<br>  Ordered At: {{ album.created }}
     </strong>

            <table class="table table-striped table-hover container">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
{% for item in album.orderitem_set.all %}

                        <tr>

                            <td>{{ item.product }}</td>

                            <td>{{ item.quantity }}</td>


                            <td>{{ item.price }} rs/</td>
                            <td>{{ item.total_i_price }} rs/</td>

                        </tr>
                {% endfor %}

                </tbody>
            </table>

<strong>          Total:{{ album.total_cost }}</strong>






      </div>
    </div>
  </div>
             {% endif %}
    {% endfor %}

</div>



        <div class="panel-group" id="accordion2" role="tablist" aria-multiselectable="true">
<h2>YOur Deleivered orders</h2>


{% for albumd in orders %}
             {% if  albumd.paid %}

  <div class="panel panel-default" style="border-radius:40px;">
    <div class="panel-heading" role="tab" id="a{{ albumd.id }}" style="padding:15px; border-radius:15px 15px 5px 5px;">
         <a role="button" data-toggle="collapse" data-parent="#accordion2" href="#{{ albumd.id }}" aria-expanded="false" aria-controls="{{ albumd.id }}" >
      <h4 class="panel-title" style="color:black;">
          Id={{ albumd.id }}  <span class="pull-right ">{{ albumd.created }}</span>
      </h4>
         </a>

    </div>
    <div id="{{ albumd.id }}" class="panel-collapse collapse " role="tabpanel" aria-labelledby="a{{ albumd.id }}">
      <div class="panel-body">


     <strong>      Ordered At: {{ albumd.created }} <br>Name={{ albumd.first_name }} &nbsp
     </strong>

            <table class="table table-striped table-hover container">
                <thead style="background-color: #5AC8FA">
                    <tr>
                           <th>Product</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
{% for item in albumd.orderitem_set.all %}

                        <tr>

                            <td>{{ item.product }}</td>

                            <td>{{ item.quantity }}</td>


                            <td>{{ item.price }} rs</td>
                            <td>{{ item.total_i_price }} rs</td>

                        </tr>
                {% endfor %}

                </tbody>
            </table>

<strong>          Total:{{ albumd.total_cost }}</strong>

          <br>


      </div>
    </div>
  </div>
             {% endif %}
    {% endfor %}

</div>











    <p class="text-right">
            <a href="{% url 'food:vegetables' %}" class="btn btn-default">Continue Shopping</a>
                        <a href="{% url 'food:cart_detail' %}" class="btn btn-primary">My Cart</a>

        </p>

  <div style="background-color: #5AC8FA">
                    <div colspan="3"></div>
      <div colspan="num" ><b><font size="15">User:{{ request.user }} </font></b></div>
    </div>
        </div>
    </div>


        {% for item in ialbum.orderitem_set.all %}

ayush

        {% endfor %}
aaa




        {% else %}
                <div class="container"  style="min-height:400px;">
                    <div class="row">
                <br>
                <a href="{% url 'main' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-shoping"></span>&nbsp; You have no Orders continue Shopping
                    </button>
                </a>
            </div>
            </div>





        {% endif %}

{% endblock %}